### ISSUE TITLE
关于输入框会自动得到焦点的问题

### ISSUE THREAD

**Issue by yunliang-ding** [react-component/input#16]
![image](https://user-images.githubusercontent.com/18275334/166884446-707acd69-2d31-4d40-aa42-2f2611bd4303.png)

当鼠标处于点击态时，将鼠标移动到输入框，此时输入框会自动得到焦点。这个是否支持关闭，或者有其他的方案处理。谢谢 🙏

**Comment by MadCcc** [comment]
Fixed in https://github.com/react-component/input/pull/13
