### ISSUE TITLE
Clear button is not accessible

### ISSUE THREAD

**Issue by vtx-anton-chashchin** [react-component/input#64]
Hello, we discovered that clear button which appears when `allowClear` property used is not accessible due to 2 reasons:
- button wrapper uses `tabindex=-1` which makes it inaccessible through the keyboard using `tab`/`shift+tab`
- button wrapper uses `span` tag which prevent to click it via `space` or `shift` when it is on focus

I opened PR to fix this and added tests to check behavior, could you check it please

https://github.com/react-component/input/pull/63

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/input/pull/63
