### ISSUE TITLE
Failed to set the 'selectionStart' property on 'HTMLInputElement': The input element's type ('email') does not support selection.

### ISSUE THREAD

**Issue by kamil-winware** [react-component/input#66]
Recent change https://github.com/react-component/input/compare/v1.4.3...v1.4.4#diff-94b5cf5856a42bc2e70f9e2b690fda2b65151186e6b007466ff6c6744c40e2c8R30 

`currentTarget.selectionStart = target.selectionStart;
  currentTarget.selectionEnd = target.selectionEnd;`

breaks input type email functionality. With error:

Failed to set the 'selectionStart' property on 'HTMLInputElement': The input element's type ('email') does not support selection.

**Comment by kamil-winware** [comment]
fix for it
[0001-fix-ignore-selection-for-input-type-email.patch](https://github.com/react-component/input/files/14559566/0001-fix-ignore-selection-for-input-type-email.patch)

**Comment by mendahu** [comment]
I have re-produced this as well.

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/input/pull/67
